### ISSUE TITLE
Release 3D layout data

### ISSUE THREAD

**Issue by skrya** [UrbanArchitect/UrbanArchitect#1]
Dear Authors, 

Thanks for the amazing work!! 

May I ask when do you plan to release the 3D layout data? Else, can you guide me on how I can build it from KITTI-360 data. 

Thanks!

**Comment by lxy198** [comment]
> Dear Authors,
> 
> Thanks for the amazing work!!
> 
> May I ask when do you plan to release the 3D layout data? Else, can you guide me on how I can build it from KITTI-360 data.
> 
> Thanks!

+1

**Comment by UrbanArchitect** [comment]
Thanks for your interests. We will release several samples of 3D layout by the end of this month.

**Comment by FanLu97** [comment]
Samples of 3D layouts are released.

**Comment by OrangeSodahub** [comment]
@FanLu97 Hi, I was wondering how to build `*.npy` data from the kitti360 dataset:
![image](https://github.com/user-attachments/assets/47ab2f83-7ff8-40ef-be13-2c47b04c41ff)

Is there any script in this repo?

**Comment by Tharun19r** [comment]
> @FanLu97 Hi, I was wondering how to build `*.npy` data from the kitti360 dataset: ![image](https://private-user-images.githubusercontent.com/54439582/355141722-47ab2f83-7ff8-40ef-be13-2c47b04c41ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTc0OTQsIm5iZiI6MTcyOTc1NzE5NCwicGF0aCI6Ii81NDQzOTU4Mi8zNTUxNDE3MjItNDdhYjJmODMtN2ZmOC00MGVmLWJlMTMtMmM0N2IwNGM0MWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTc2ZWEwMjA1YTA0NTdmYTE3OGJkNTQ2ZTZjYzI0ZGZlMTBkMDk0NzdlNDVmOGFjODNjMTczNDA3MzFhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GVkBsgOHhIIX-PQe3bretULafQHdq44tOA5ficdMGf8)
> 
> Is there any script in this repo?

+1
